### ISSUE TITLE
the "this" context of type....

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/template-master-detail-ng#78] opened 2017-09-30 01:33 UTC
severity: 'Error'
message: 'The 'this' context of type 'BehaviorSubject<ActivatedRoute>' is not assignable to method's 'this' of type 'Observable<ActivatedRoute>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<ActivatedRoute, R>) => Observable<ActivatedRoute>' is not assignable to type '<R>(operator: Operator<ActivatedRoute, R>) => Observable<R>'.
      Type 'Observable<ActivatedRoute>' is not assignable to type 'Observable<R>'.
        Type 'ActivatedRoute' is not assignable to type 'R'.'
at: '32,13'
source: 'ts'

**Comment by MIYankov** [comment] 2017-10-02 09:29
@nelsonwilliam11 I can't reproduce this error no matter what I try. Can you provide some steps to reproduce this? The issue seems very reminiscent of [this](https://github.com/ReactiveX/rxjs/issues/2539) in rxjs, but it should be fixed and I couldn't reproduce it.

**Comment by nelsonwilliam11** [comment] 2017-10-03 04:10
this is all did 
`import { PageRoute, RouterExtensions } from "nativescript-angular/router";
import { Component, OnInit } from "@angular/core";
import 'rxjs/add/operator/switchMap';

import { Car } from "../../shared/car.model";
import { CarService } from "../../shared/car.service";

 
@Component({
    selector: "sqlite",
    moduleId: module.id,
    templateUrl: "sqlite.html",
})
export class SqliteComponent implements OnInit {
 
    private _car: Car;
    
        constructor(
            private _carService: CarService,
            private _pageRoute: PageRoute,
            private _routerExtensions: RouterExtensions
            
        ) { }
    
      
        ngOnInit(): void {
            let carId = "";
        
            this._pageRoute.activatedRoute
                .switchMap((activatedRoute) => activatedRoute.params)
                .forEach((params) => {
                    carId = params.id;
                });
    
            this._car = this._carService.getCarById(carId);
            }
    
        get car(): Car {
            return this._car;
        }
    
        /* ***********************************************************
        * The back button is essential for a master-detail feature.
        *************************************************************/
        onBackButtonTap(): void {
            this._routerExtensions.backToPreviousPage();
        }
    
        /* ***********************************************************
        * The master-detail template comes with an example of an item edit page.
        * Check out the edit page in the /cars/car-detail-edit folder.
        *************************************************************/
        onEditButtonTap(): void {
            this._routerExtensions.navigate(["/cars/car-detail-edit", this._car.id],
            {
                animated: true,
                transition: {
                    name: "slideTop",
                    duration: 200,
                    curve: "ease"
                }
            });
        }
    }
`
and this where the error is 
`    this._pageRoute.activatedRoute
`

**Comment by MIYankov** [comment] 2017-10-03 08:27
This issue is indeed connected to Rxjs and is fixed in their latest version. Take a look at this PR we made some time ago - https://github.com/NativeScript/template-drawer-navigation-ng/commit/19be0d59b5515d45528951d359e62f97455f0a63 . Try updating rxjs and see if this fixes the issue.

**Comment by nelsonwilliam11** [comment] 2017-10-03 22:18
@MIYankov  if you may tell me whats the command for updating Rxjs??

**Comment by MIYankov** [comment] 2017-10-04 08:43
@nelsonwilliam11 That would be `npm install --save rxjs`. You can check your dependency versions in the package.json file in the root of your project.

**Comment by nelsonwilliam11** [comment] 2017-10-04 16:02
thanks @MIYankov  updating rjxs sloved the problem

**Closed** 2017-10-05 07:54 UTC
